language: go
go:
  - 1.1
  - 1.2
  - 1.3
  - release
  - tip
install:
  - echo "Skip install"
script:
  - export PCT_TEST_MYSQL_DSN='travis:@tcp(127.0.0.1:3306)/?parseTime=true'
  - export PCT_TEST_MYSQL_ROOT_DSN='root:@tcp(127.0.0.1:3306)/'
  - test/runner.sh -u
